### ISSUE TITLE
speedometer isn't disabling 

### ISSUE THREAD

**Issue by Macintosh12684** [PapaPeach/xhud#13]
my speedometer won't turn off nor does any customizations work either due to something it keeps saying "writing bindings to c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\cfg\xhud_customizations_selection.txt" but it still doesn't work

**Comment by leofleeo** [comment]
try going to  c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\cfg\ in your file manager and check if there is a file called xhud_customizations_selection.txt. If there is, try deleting it. If that file isn't present try creating a blank file called xhud_customizations_selection.txt

**Comment by leofleeo** [comment]
I don't think it'll fix anything but you can try it

**Comment by Macintosh12684** [comment]
ight i'll let you know
