### ISSUE TITLE
Cannot select resolution

### ISSUE THREAD

**Issue by leofleeo** [PapaPeach/xhud#14]
I have temporarily removed all my mods from the tf/custom folder and I still cannot select my resolution. I am on openSUSE linux and I am on a 1920x1080 screen. I also tried deleting all xhud config files but that didn't work. Here's a video:

https://github.com/PapaPeach/xhud/assets/83542885/428d3a95-e5be-4232-aaad-3ff130ac1a75

**Comment by Dupiter-AU** [comment]
Found a workaround;
- Create `xhud_resolution_selection.txt` in xhud/cfg
- In the file, paste this text, but change the resolution to your own: `#base ../resolutions/16x9_2560x1440/override.res
` (The selection of resolutions can be found in `xhud/resolutions`)
- xhud then successfully loads to the main menu on the next boot.

I don't know why xhud fails to create this file on linux ¯\_(ツ)_/¯

**Comment by leofleeo** [comment]
tysm that worked!

**Comment by leofleeo** [comment]
The text cuts off, things overlap even with the correct resolution selected, and the customizations don't work :(. Guess I'm sticking to hypnotize HUD.

**Comment by Dupiter-AU** [comment]
yeah... it's pretty broken on linux sady :(

**Comment by Kurumi78** [comment]
For clarity sake, the issue with customizations and resolution not saving is due to how directories are listed on windows vs linux. I got around these issues by changing lines in the config to the direct path of the xhud folder which seemingly fixed the issues. I have not fixed text cutoff yet however.
