### ISSUE TITLE
Resolution and hidden screen problems

### ISSUE THREAD

**Issue by Polarite** [PapaPeach/xhud#15]
when playing MvM in 2560x1440 screen I have to reset the resolution every time I open the screen. because the wave bar is too much to the left
extra issues are
 when I am in customizations screen of hud and exit the pause menu my mouse is still on screen and I cant look around.
mission completed screen is empty after resetting the resolution

except that so much customizations and its amazing!

**Comment by Polarite** [comment]
![image](https://github.com/PapaPeach/xhud/assets/34978332/4464998a-c675-471c-a37c-2e65a412021a)
example after resetting resolution^

**Comment by Polarite** [comment]
![image](https://github.com/PapaPeach/xhud/assets/34978332/209530c2-4dac-4361-8dc4-cdc9d385581e)
theres also some overlap

I am just listing stuff that I see.

**Comment by Polarite** [comment]
![image](https://github.com/PapaPeach/xhud/assets/34978332/a413db0a-65b3-4ede-8d7a-6d958ba0895f)
max health isnt relative to the upgrades in mvm, so blue bar fills earlier than max health does

**Comment by PapaPeach** [comment]
> when playing MvM in 2560x1440 screen I have to reset the resolution every time I open the screen. because the wave bar is too much to the left extra issues are when I am in customizations screen of hud and exit the pause menu my mouse is still on screen and I cant look around. mission completed screen is empty after resetting the resolution
> 
> except that so much customizations and its amazing!

- The mvm wave bar fix is on the development branch and will be pushed to release soon.
- The screen being locked because of the customization menu has been fixed (it's a bug that happens in the base game if you exit the training menu while in game apparently).


> ![image](https://private-user-images.githubusercontent.com/34978332/241797977-4464998a-c675-471c-a37c-2e65a412021a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjYzMzQsIm5iZiI6MTcyMDU2NjAzNCwicGF0aCI6Ii8zNDk3ODMzMi8yNDE3OTc5NzctNDQ2NDk5OGEtYzY3NS00NzFjLWEzN2MtMmU2NWE0MTIwMjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NWFmZmY3ZTA0NGZiZTIzODg3NGIzMjE3OTcyN2I4MzlkYmViZGZkODFkNmVhZWI4MzllYmE2MTMxMDdlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GWjcpsvyXqO0RJl3HRMhDR30DIwE5dc7j2UcnJGWwLY) example after resetting resolution^

- This bug still occurs, the hud community hasn't figured out why it specifically happens, but reloading the hud during the session seems to have some impact on increasing the likelihood of this happening. Hopefully the first fix mentioned decreases the need for reloads that might contribute to this issue.


> ![image](https://private-user-images.githubusercontent.com/34978332/241798775-209530c2-4dac-4361-8dc4-cdc9d385581e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjYzMzQsIm5iZiI6MTcyMDU2NjAzNCwicGF0aCI6Ii8zNDk3ODMzMi8yNDE3OTg3NzUtMjA5NTMwYzItNGRhYy00MzYxLThkYzQtY2RjOWQzODU1ODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMzk5YjY2MWI5MmNjNDU5NDQ5MDFhN2ZjMzNiMmRjNjgzMzU1Yzg5ZjU5NWIwOGRmYjM4ODk0MDU1NjA0MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMk1X_8PM5z1QJxQl6_0eXJltSzLtswoNK5o0y_dXp0) theres also some overlap
> 
> I am just listing stuff that I see.

- Fixed in the most recent update.


> ![image](https://private-user-images.githubusercontent.com/34978332/241803289-a413db0a-65b3-4ede-8d7a-6d958ba0895f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjYzMzQsIm5iZiI6MTcyMDU2NjAzNCwicGF0aCI6Ii8zNDk3ODMzMi8yNDE4MDMyODktYTQxM2RiMGEtNjViMy00ZWRlLThkN2EtNmQ5NThiYTA4OTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIzMDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNzZhMjk3MDEzYTM1MTUyYjRkMjVjYTdiOTRhNjlmNmE1YTgwNzA0NmQzYmMyYTI0Y2U0ZTYwZDMzNTc1MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4uzaUf1PzfMfjde4-g4DfMOHzX35vsCzN0hmjs0ZZZ4) max health isnt relative to the upgrades in mvm, so blue bar fills earlier than max health does

- Unfortunately that's a limitation in the implementation. The mvm upgrade increases over healing without affecting base health, which means that the expanding health icon I use to create the health bar simply scales beyond what is showable. Hopefully it isn't too disruptive as it still effectively indicates that the target is healthy AF.

Glad to see you are (were?) enjoying the hud!
