### ISSUE TITLE
Random recharging bar appears.

### ISSUE THREAD

**Issue by ghamayyameen** [PapaPeach/xhud#16]
the bar can be fixed by reloading the hud, but the problem reappears after a little while. iirc this started happening after i added crosshairs from master comfig. I don't seem to have this issue in other huds.

**Comment by ghamayyameen** [comment]
it appears when i use a voice line from the voice menu. if i use the voice menu again after the bar appears, the bar resets, and it starts going up again.

**Comment by PapaPeach** [comment]
That's the "Uber Tracker" customization you've enabled in the customization menu. When you close the voice menu it triggers a timer that roughly estimates the enemy medic's uber.
