### ISSUE TITLE
Ammonoclip Hidden for many weapons

### ISSUE THREAD

**Issue by sultan8982** [PapaPeach/xhud#18]
So far It's been hidden with iron bomber, all rocket launchers and rocket jumper, and medics crossbow.
Only shows ammo in clip.  This frequently happens and when it does it doesn't go away even after starting new sessions. I reinstalled (which seems to be the only way to fix it) and when I set up customizations it happened again. 

![Team Fortress 2 31_07_2023 8_43_11 PM](https://github.com/PapaPeach/xhud/assets/137390351/f041bfbb-8c60-4c4f-ae0f-1e062b18747b)

**Comment by PapaPeach** [comment]
Are there any hud related errors in console when you launch the game or select a class?
