### ISSUE TITLE
Hud shows "%active" under the crosshair when playing demoman

### ISSUE THREAD

**Issue by dbt0815** [PapaPeach/xhud#19]
Hud shows "%active" under the crosshair when playing demoman

what can i do to make it dissapear?

https://imgur.com/a/jNmGnMC

edit: asked on discord and got told to fire a stick to work around it.

**Comment by Niterux** [comment]
This is a Team Fortress 2 bug and happens with every HUD including the default one (without using a custom font to hide the %,a,c,t,i,v,e characters), ask Valve to fix it!
