### ISSUE TITLE
xhud crashes the game

### ISSUE THREAD

**Issue by impale1** [PapaPeach/xhud#20]
This happens in both the release and development branches

1. Use this method to reset the TF2 to default settings https://docs.comfig.app/latest/setup/clean_up/
2. Install xhud
3. Start TF2
4. Select 1920x1080 resolution
5. Click the "Game" button in the upper right corner
6. The game will crash without error message

The game will continue to crash in the same place until you uninstall xhud and read the popups using the default hud, then install xhud again, at which point the game will no longer crash

Resolution: 1920x1080
Operating system: Windows 11 Enterprise 22H2

**Comment by PapaPeach** [comment]
Should now be fixed in [this update](https://github.com/PapaPeach/xhud/commit/1186cf2f069028ce8d00d34acd45565abd2eae90) to the development branch.
