### ISSUE TITLE
I'd like to request 1920x1200 19:10 as a resolution.

### ISSUE THREAD

**Issue by GrelTheL** [PapaPeach/xhud#3]
Might help out some people with older monitors. Thanks

**Comment by PapaPeach** [comment]
For the current roadmap that falls below my usage threshold for supported resolutions, with only [0.59% of all Steam users running that resolution](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam).

A work around is to round down to the nearest supported 16:10 resolution, as that adverse effect of doing so is simply that your health will display a few health-points higher than it actually is on the healthbar. 
The formula for making your own override values to support your resolution are also commented in the files that the resolution override files are based on if you'd like a more hands on fix.
