### ISSUE TITLE
TargetID low health indicator

### ISSUE THREAD

**Issue by bug4708** [PapaPeach/xhud#33]
Is there a way to add an option to make the targetid health bar turn a certain color when players are low? I'm trying to figure out how to change the color to yellow but I'm not sure what I'm doing. This would be a good option to have in the hud editor as a selectable color.

**Comment by PapaPeach** [comment]
Unfortunately this is not possible. The health bars in Xhud rely on the low-health threshold being at 100% health, which would make low health warnings as described function counterintuitively.

**Comment by bug4708** [comment]
Thank you for explaining, I don't have a lot of experience with editing huds. I changed the background for the health bar to be .../panels/tig_red (not exact file path) and that made reading it a lot more intuitive.
