### ISSUE TITLE
Can't see my own chat messages or voise messages

### ISSUE THREAD

**Issue by Xyeflo** [PapaPeach/xhud#7]
Like the title, I can't see my OWN messages but it's perfectly see others. idk what to do to fix it.

**Comment by PapaPeach** [comment]
![20230221223728_1](https://user-images.githubusercontent.com/56094487/220515382-aceeaab3-be31-4197-82af-bcaf2af3ddef.jpg)
Works fine for me. Not sure it's hud related.

**Comment by Xyeflo** [comment]
hm

**Comment by Xyeflo** [comment]
it's been a few days and i still can't see mine.

**Comment by Xyeflo** [comment]
ok, it's fixed now.

**Comment by sweglord227** [comment]
you likely muted yourself in game. not a hud issue.
